version: 2.1

executors:
  basic:
    docker:
      - image: cimg/base:stable

commands:
  bootstrap:
    description: Bootstraps the NodeJS environment along with Yarn and the project dependencies
    parameters:
      nodejs:
        description: The NodeJS version to install
        type: string

    steps:
      - checkout:
          path: ~/repos/rxjs-axios

      - run:
          name: Install NVM
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install NodeJS v<< parameters.nodejs >>
          command: |
            nvm install << parameters.nodejs >>
            nvm use << parameters.nodejs >>
            nvm alias default << parameters.nodejs >>
            node --version

      - run:
          name: Install yarn
          command: npm install -g yarn

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install packages
          command: yarn install --immutable

      - save_cache:
          paths:
            - ~/repos/rxjs-axios/.yarn/cache
          key: yarn-v1-{{ checksum "yarn.lock" }}

jobs:
  build:
    working_directory: ~/repos/rxjs-axios
    executor: basic
    parameters:
      nodejs:
        description: The NodeJS version to install
        type: string
      rxjs:
        description: The RxJS version to use
        type: string
      axios:
        description: The Axios version to use
        type: string

    steps:
      - bootstrap:
          nodejs: << parameters.nodejs >>

      - run:
          name: Install RxJS v<< parameters.rxjs >>
          command: yarn add --dev rxjs@^<< parameters.rxjs >>

      - run:
          name: Install Axios v<< parameters.rxjs >>
          command: yarn add --dev axios@^<< parameters.axios >>

      - run:
          name: Compile
          command: yarn compile

      - run:
          name: Lint
          command: yarn lint

      # Enable once tests are added
      # - run:
      #     name: Test
      #     command: yarn test --forbid-only

workflows:
  main:
    jobs:
      - build:
          matrix:
            parameters:
              nodejs: ["16", "17", "18", "19"]
              rxjs: ["7.5.7", "6.6.7", "5.5.12"]
              axios: ["1.1.3", "1.0.0"]
